### ISSUE TITLE
Issue running with Keras v2.4.3

### ISSUE THREAD

**Issue by edwinpalegre** [run-ai/runai#21]
I seem to have encountered an issue when running RunAI with the current version of Keras as of the writing of this post (v2.4.3). I've run the following commands below

`import keras
import runai.ga.keras

opt = keras.optimizers.SGD()
opt = runai.ga.keras.optimizers.Optimizer(opt, steps=5)`

Running that code creates the following error
------------------------------------------------------------------------------------
Traceback (most recent call last):

  File "<ipython-input-3-d3a9effcdcac>", line 2, in <module>
    ga_optimizer = runai.ga.keras.optimizers.Optimizer(sgd_optimizer, steps=5)

  File "$PYTHONPATH\lib\site-packages\runai\ga\keras\optimizers.py", line 12, in __init__
    super(Optimizer, self).__init__()

TypeError: __init__() missing 1 required positional argument: 'name'

----------------------------------------------------------------------------------------

I've tried to see what the cause of the issue was and ran this code with another computer running an older version of Keras. I ran it on Keras v2.3.1 and it actually imported properly with no issues. I didn't train the model, however, so I'm not sure if it works past that but I have no reason to believe it wouldn't. Consequently, using that same computer and uninstalling Keras v2.3.1 and installing v2.4.3 does give me the same error listed above, which is how I came to this conclusion.

**Comment by levosos** [comment]
Hi @edwinpalegre and thanks for the issue!

Indeed, you are right. The implementation of `keras.optimizers.Optimizer` (optimizers.py) was removed in Keras v2.4.0 and is now a redirection to `tensorflow.optimizers.Optimizer`. The Run:AI Python library GA and Elasticity mechanisms are built around the previous implementation (which are not available anymore in your version of Keras).

Unfortunately, we haven't yet found the time to add support of `tf.keras` (TF 2.x) to the Run:AI Python library, and this will probably not be done in the near future.

You can downgrade your Keras version to v2.2.4 (this one was tested, although v2.3.0 might also work) to use the Run:AI Python library until we'll add the support.

In addition, we'll happily receive contributions if you find the time to add the support yourself.

Thanks again for letting us know,
Raz.
